dist: trusty
sudo: required
language: cpp
addons:
  apt:
    packages:
    - cmake
    - libblas3gf
    - libopenblas-base
    - libopenblas-dev
    - liblapack3
    - liblapack-dev
compiler:
- clang
- gcc
before_install:
- travis/install_armadillo.sh
- travis/install_gig.sh
- sudo ldconfig
script:
- mkdir build && pushd build && cmake .. && make
- ls /usr/local/lib/
- make test ARGS="-V"
- popd
- rm -rf build
notifications:
  email: false
deploy:
  provider: releases
  api_key:
    secure: jT/bfeIfcOKeHdxQmPEpvbV8swXAoSavVcNKXZGN4j0RTpUfvS0I9RGqX8KKzq5RamVwpFiMNFtDlKO8tebb3xl7BIkF6UQU7xVuoINWsDnqLOjrJV+SLv209YS9mF9A35l4uOndjX6luKKOFGsJ7K+2cR2Db2SZx9hw7qXw61Rm+EHLrC9ZKsCDpCTVI0UsP9gSpSZ/33KruaW3Ed6fq/+bKmqXJF6mK70ivT2mXTKvonegAo33ILT5aD3WXXHRVWxFqSI9tKLtuYe12qPmC6Cw8uIkM9U1msSzJhEuWQbrqkYkOiRNVO/hTLGHvv84Y9lfRGPTLbYWk5+ZAf+UGnI3EE5IaivZPKxf3FbX0/FeJQn8ffdOjAkF057dKkuMO5c+CNICM97Ae3tgeAe237b+61J6oLkcnRtDZJQmu+/kDByJp0WU2d+XSRm1IRENz+VCvfNZthJMXqeD/1H3LbNE8iJKrCpMe/r67RVa1lkea93Qe37e3E7YY3q/rGhkBOd/Z1eTkq+huha4sivuDNfIUhfuoK0MIxuH3wMj3RUAc5h5TnWNVumWng9DdwA4zXN/hnvE6mHfGlQHhSAwkMUQ85V+4NSW3FWpvS25stdT14hVi292idlaCzamBGHtw8mCMqcHIezkKAckkfWRiFqQDO4AVbJ0l2ecJqCVAyw=
  on:
    tags: true
    repo: Horta/BASiCS
    condition: "$CC = clang"
